
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: flussonic
  version: '19.08' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Flussonic streaming server
  description: |
    This is a multifunctional platform video streaming server
    capable to ingest, record, transcode and stream video.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
